apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-argocd-http
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80
    host: argocd.127.0.0.1.nip.io
  tls:
  - hosts:
    - argocd.127.0.0.1.nip.io
    secretName: argocd-ingress-http